"
Es un polígono regular de 4 lados.
"
Class {
	#name : 'Cuadrado',
	#superclass : 'Forma',
	#instVars : [
		'norte',
		'sur',
		'este',
		'oeste'
	],
	#category : 'Laberinto26-Solucion',
	#package : 'Laberinto26',
	#tag : 'Solucion'
}

{ #category : 'accessing' }
Cuadrado >> este [

	^ este
]

{ #category : 'accessing' }
Cuadrado >> este: anObject [

	este := anObject
]

{ #category : 'accessing' }
Cuadrado >> norte [

	^ norte
]

{ #category : 'accessing' }
Cuadrado >> norte: anObject [

	norte := anObject
]

{ #category : 'accessing' }
Cuadrado >> oeste [

	^ oeste
]

{ #category : 'accessing' }
Cuadrado >> oeste: anObject [

	oeste := anObject
]

{ #category : 'accessing' }
Cuadrado >> sur [

	^ sur
]

{ #category : 'accessing' }
Cuadrado >> sur: anObject [

	sur := anObject
]
