"
Orientacion define la interfaz de las orientaciones de los contenedores
"
Class {
	#name : 'Orientacion',
	#superclass : 'Object',
	#category : 'Laberinto26',
	#package : 'Laberinto26'
}

{ #category : 'as yet unclassified' }
Orientacion >> ponerElemento:unEM enContenedor:unCont [

	self subclassResponsibility 
]

{ #category : 'as yet unclassified' }
Orientacion >> recorrer:unBloque enContenedor:unCont [

	self subclassResponsibility 
]
