"
Rombo es un polígono con orientaciones ne no se so
"
Class {
	#name : 'Rombo',
	#superclass : 'Forma',
	#instVars : [
		'ne',
		'no',
		'se',
		'so'
	],
	#category : 'Laberinto26-Solucion',
	#package : 'Laberinto26',
	#tag : 'Solucion'
}

{ #category : 'accessing' }
Rombo >> ne [

	^ ne
]

{ #category : 'accessing' }
Rombo >> ne: anObject [

	ne := anObject
]

{ #category : 'accessing' }
Rombo >> no [

	^ no
]

{ #category : 'accessing' }
Rombo >> no: anObject [

	no := anObject
]

{ #category : 'accessing' }
Rombo >> se [

	^ se
]

{ #category : 'accessing' }
Rombo >> se: anObject [

	se := anObject
]

{ #category : 'accessing' }
Rombo >> so [

	^ so
]

{ #category : 'accessing' }
Rombo >> so: anObject [

	so := anObject
]
