"
Define la interfaz de los visitantes (patrón Visitor)
"
Class {
	#name : 'Visitor',
	#superclass : 'Object',
	#category : 'Laberinto26-Visitor',
	#package : 'Laberinto26-Visitor'
}

{ #category : 'visitor' }
Visitor >> visitarArmario:unArmario [
]

{ #category : 'visitor' }
Visitor >> visitarBomba:unaBomba [
]

{ #category : 'visitor' }
Visitor >> visitarHabitacion:unaHab [
]

{ #category : 'visitor' }
Visitor >> visitarPared:unaPared [
]

{ #category : 'visitor' }
Visitor >> visitarPuerta:unaPuerta [
]

{ #category : 'visitor' }
Visitor >> visitarTunel:unTunel [
]
